 // API ENDPOINTS USERS //

// GET ALL USERS WITHOUT PASS
GET http://localhost:3000/api/users/all

###

// GET SPECIFIC USER WITHOUT PASS
GET http://localhost:3000/api/users/2

###

// LOGIN USER 
POST http://localhost:3000/api/users/login 
Content-Type: application/json

{
 "email": "test@mail.com", 
 "password": "test"
}

###

// CREATE NEW USER
POST http://localhost:3000/api/users/add 
Content-Type: application/json

{
 "name": "Test Testssond", "email": "test123@mail.com", "password": "test"
}

###


