 // API ENDPOINTS USERS - DONT KNOW HOW TO IMPLEMENT COOKIES HERE //

// GET ALL USERS WITHOUT PASS
GET http://localhost:3000/api/users/all

###

// GET SPECIFIC USER WITHOUT PASS
GET http://localhost:3000/api/users/ac19f9b6-8041-44bd-ac2d-8a87f371b4a2

###

// LOGIN USER 
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
 "email": "kalle@mail.com", 
 "password": "kalle"
}

###

// CREATE NEW USER
POST http://localhost:3000/api/users/add 
Content-Type: application/json

{
 "name": "Test Testssond", "email": "test123@mail.com", "password": "test"
}

###


